# Generated by Django 2.2.1 on 2019-05-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModelName',
            new_name='Todo',
        ),
    ]
