# Generated by Django 2.2.1 on 2019-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190504_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
